"""Built-in wordlist of common weak HMAC secrets used with `--crack` when no
wordlist file is given. Sourced from the usual suspects: default/placeholder
values shipped in tutorials and boilerplate, plus generically weak passwords
that show up in every leaked-credential list.
"""

from __future__ import annotations

DEFAULT_WORDLIST: list[str] = [
    "secret",
    "Secret",
    "secret123",
    "password",
    "Password",
    "password123",
    "changeme",
    "changethis",
    "changeit",
    "your-256-bit-secret",
    "your-secret-key",
    "your-secret-key-here",
    "supersecret",
    "super-secret",
    "supersecretkey",
    "mysecret",
    "my-secret",
    "jwtsecret",
    "jwt-secret",
    "jwt_secret",
    "signingkey",
    "signing-key",
    "test",
    "testing",
    "dev",
    "development",
    "development-secret",
    "development-only-secret",
    "local",
    "localhost",
    "admin",
    "administrator",
    "letmein",
    "qwerty",
    "12345678",
    "123456789",
    "0123456789",
    "abcdefgh",
    "default",
    "defaultsecret",
    "key",
    "apikey",
    "api-key",
    "api_key",
    "token",
    "authsecret",
    "auth-secret",
    "companyname",
    "acme",
    "acme-secret",
    "insecure",
    "notsecure",
    "not-a-secret",
]
